export const CONFIG = {
    PLAYER_RADIUS: 15,
    BALL_RADIUS: 8,
    PLAYER_SPEED: 3,
    FRICTION: 0.98,
    BOUNCE_LOSS: 0.8,
    KICK_STRENGTH: 10,
    OFFENSIVE_KICK_STRENGTH: 10,
    CLEARANCE_KICK_STRENGTH: 15,
    KICK_RADIUS_MULTIPLIER: 1.5,
    GOAL_MESSAGE_DURATION: 2000,
    GAME_DURATION_SECONDS: 5 * 60,
    GAME_START_COOLDOWN: 500
};

export const COLORS = {
    BLUE_PLAYER: '#4299e1',
    RED_PLAYER: '#e53e3e',
    BALL: '#fff',
    FIELD_LINES: '#e2e8f0',
    PLAYER_SHADOW: 'rgba(0,0,0,0.3)'
};